export type ColorPaletteItem = {
  label: string;
  value: string;
};

export const sheetFillPalette: ColorPaletteItem[] = [
  { label: "검정", value: "#000000" },
  { label: "진회색", value: "#404040" },
  { label: "회색", value: "#737373" },
  { label: "연회색", value: "#a3a3a3" },
  { label: "밝은 회색", value: "#d4d4d4" },
  { label: "흰색", value: "#ffffff" },
  { label: "빨강", value: "#ff0000" },
  { label: "주황", value: "#ff9900" },
  { label: "노랑", value: "#ffff00" },
  { label: "초록", value: "#00ff00" },
  { label: "청록", value: "#00ffff" },
  { label: "파랑", value: "#0000ff" },
  { label: "남색", value: "#4f46e5" },
  { label: "보라", value: "#9900ff" },
  { label: "분홍", value: "#ff00ff" },
  { label: "연빨강", value: "#f4cccc" },
  { label: "연주황", value: "#fce5cd" },
  { label: "연노랑", value: "#fff2cc" },
  { label: "연초록", value: "#d9ead3" },
  { label: "연청록", value: "#d0e0e3" },
  { label: "연파랑", value: "#cfe2f3" },
  { label: "연남색", value: "#d9d2e9" },
  { label: "연보라", value: "#ead1dc" },
  { label: "중간 빨강", value: "#e06666" },
  { label: "중간 주황", value: "#f6b26b" },
  { label: "중간 노랑", value: "#ffd966" },
  { label: "중간 초록", value: "#93c47d" },
  { label: "중간 청록", value: "#76a5af" },
  { label: "중간 파랑", value: "#6fa8dc" },
  { label: "중간 남색", value: "#8e7cc3" },
  { label: "중간 보라", value: "#c27ba0" },
  { label: "진빨강", value: "#cc0000" },
  { label: "진주황", value: "#e69138" },
  { label: "진노랑", value: "#f1c232" },
  { label: "진초록", value: "#6aa84f" },
  { label: "진청록", value: "#45818e" },
  { label: "진파랑", value: "#3d85c6" },
  { label: "진남색", value: "#674ea7" },
  { label: "진보라", value: "#a64d79" },
  { label: "어두운 빨강", value: "#990000" },
  { label: "어두운 주황", value: "#b45f06" },
  { label: "어두운 노랑", value: "#bf9000" },
  { label: "어두운 초록", value: "#38761d" },
  { label: "어두운 청록", value: "#134f5c" },
  { label: "어두운 파랑", value: "#0b5394" },
  { label: "어두운 남색", value: "#351c75" },
  { label: "어두운 보라", value: "#741b47" },
];
