ALTER TABLE "OmrUpload" ADD COLUMN "phoneLast8" TEXT;
ALTER TABLE "OmrUpload" ADD COLUMN "matchStatus" TEXT NOT NULL DEFAULT 'NEEDS_PHONE';
ALTER TABLE "OmrUpload" ADD COLUMN "recognizeStatus" TEXT NOT NULL DEFAULT 'WAITING';
ALTER TABLE "OmrUpload" ADD COLUMN "gradingStatus" TEXT NOT NULL DEFAULT 'WAITING';
ALTER TABLE "OmrRecognizedAnswer" ADD COLUMN "finalAnswer" TEXT;
